service: lambda-resize-images-list

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  memorySize: 256
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
        - s3:DeleteObject
      Resource:
        - arn:aws:s3:::*

functions:
  resize:
    handler: handler.handle
    environment:
      bucket: natalsimpatia2021
      width: 864
      height: 314
      quality: 80
      target: optimized
      prefix: list_
      suffix: _optimized
    events:
      - s3:
          bucket: natalsimpatia2021
          existing: true
          event: s3:ObjectCreated:*
          rules:
            - prefix: list
            - suffix: .jpg
      - s3:
          bucket: natalsimpatia2021
          existing: true
          event: s3:ObjectCreated:*
          rules:
            - prefix: list
            - suffix: .jpeg
      - s3:
          bucket: natalsimpatia2021
          existing: true
          event: s3:ObjectCreated:*
          rules:
            - prefix: list
            - suffix: .png
